aggregation_function: sum
batch_size: 1024
drop_p: 0.1
hidden_layers:
- 32
input_size: 18
lr: 0.0003
transform: !!python/object:data.datamodule.MaxMin
  params:
    his:
      max: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADE3ODc3NjIwNDhxAlgDAAAAY3B1cQNLAk50cQRRLoACXXEAWAoAAAAxNzg3NzYy
          MDQ4cQFhLgIAAAAAAAAAAABRQ2jJlEk=
      - 0
      - !!python/tuple
        - 2
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      min: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADE2Mzk0MTA0ODBxAlgDAAAAY3B1cQNLAk50cQRRLoACXXEAWAoAAAAxNjM5NDEw
          NDgwcQFhLgIAAAAAAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple
        - 2
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    target:
      max: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCQAAADE2Mjk0MjU5MnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADE2Mjk0MjU5
          MnEBYS4BAAAAAAAAAAAAUUM=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      min: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCQAAADE1ODE3MDAzMnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADE1ODE3MDAz
          MnEBYS4BAAAAAAAAAAAAyEE=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    weather:
      max: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCQAAADE2MTM2MDk0NHECWAMAAABjcHVxA0sDTnRxBFEugAJdcQBYCQAAADE2MTM2MDk0
          NHEBYS4DAAAAAAAAAM3MnEAAAIA/mpkvQg==
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      min: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADI1NDQzODE3MjhxAlgDAAAAY3B1cQNLA050cQRRLoACXXEAWAoAAAAyNTQ0Mzgx
          NzI4cQFhLgMAAAAAAAAAmpmZwQAAAAAzMzM/
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
weight_decay: 5.0e-05
