aggregation_function: sum
batch_size: 1024
drop_p: 0.1
hidden_layers:
- 32
input_size: 12
lr: 0.0003
transform: !!python/object:data.datamodule.MaxMin
  params:
    his:
      max: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADEyMDUyMTQ4OTZxAlgDAAAAY3B1cQNLAk50cQRRLoACXXEAWAoAAAAxMjA1MjE0
          ODk2cQFhLgIAAAAAAAAAAADUQtiLy0o=
      - 0
      - !!python/tuple
        - 2
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      min: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADE1OTgyNzg2NTZxAlgDAAAAY3B1cQNLAk50cQRRLoACXXEAWAoAAAAxNTk4Mjc4
          NjU2cQFhLgIAAAAAAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple
        - 2
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    target:
      max: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADI1MDE2MDg0ODBxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAyNTAxNjA4
          NDgwcQFhLgEAAAAAAAAAAADUQg==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      min: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADI1MDEzMzM2MDBxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAyNTAxMzMz
          NjAwcQFhLgEAAAAAAAAAAAAAAA==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    weather:
      max: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCQAAADE0Mjc1NDkxMnECWAMAAABjcHVxA0sDTnRxBFEugAJdcQBYCQAAADE0Mjc1NDkx
          MnEBYS4DAAAAAAAAAM3M3EGamRk/AAD4QQ==
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      min: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADEyMDQ1ODU1NjhxAlgDAAAAY3B1cQNLA050cQRRLoACXXEAWAoAAAAxMjA0NTg1
          NTY4cQFhLgMAAAAAAAAAMzMzwAAAAACamTlA
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
weight_decay: 5.0e-05
