aggregation_function: sum
batch_size: 1024
drop_p: 0.1
hidden_layers:
- 32
input_size: 27
lr: 0.0003
transform: !!python/object:data.datamodule.MaxMin
  params:
    his:
      max: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADE3MDQ3ODE1NTJxAlgDAAAAY3B1cQNLAk50cQRRLoACXXEAWAoAAAAxNzA0Nzgx
          NTUycQFhLgIAAAAAAAAAAADkQp1iE0s=
      - 0
      - !!python/tuple
        - 2
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      min: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADE2OTcxMjk5MjBxAlgDAAAAY3B1cQNLAk50cQRRLoACXXEAWAoAAAAxNjk3MTI5
          OTIwcQFhLgIAAAAAAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple
        - 2
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    target:
      max: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADE3MTI2OTM2OTZxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAxNzEyNjkz
          Njk2cQFhLgEAAAAAAAAAAADkQg==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      min: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADE3MTgxMDEwNDBxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAxNzE4MTAx
          MDQwcQFhLgEAAAAAAAAAAAAAAA==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    weather:
      max: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADE3Mzk2NTcyOTZxAlgDAAAAY3B1cQNLA050cQRRLoACXXEAWAoAAAAxNzM5NjU3
          Mjk2cQFhLgMAAAAAAAAAZmb6QQAA4EAzMztC
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      min: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCQAAADE2NTMyMjMzNnECWAMAAABjcHVxA0sDTnRxBFEugAJdcQBYCQAAADE2NTMyMjMz
          NnEBYS4DAAAAAAAAAAAAQMEAAAAAAAAAAA==
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
weight_decay: 5.0e-05
