aggregation_function: sum
batch_size: 1024
drop_p: 0.1
hidden_layers:
- 32
input_size: 27
lr: 0.0003
transform: !!python/object:data.datamodule.MaxMin
  params:
    his:
      max: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADE3NDA5ODQ2MjRxAlgDAAAAY3B1cQNLAk50cQRRLoACXXEAWAoAAAAxNzQwOTg0
          NjI0cQFhLgIAAAAAAAAAAADkQp1iE0s=
      - 0
      - !!python/tuple
        - 2
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      min: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCQAAADE3NTE3MjQxNnECWAMAAABjcHVxA0sCTnRxBFEugAJdcQBYCQAAADE3NTE3MjQx
          NnEBYS4CAAAAAAAAAAAAAAAAAAAA
      - 0
      - !!python/tuple
        - 2
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    target:
      max: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADI3MDMyNzE0NTZxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAyNzAzMjcx
          NDU2cQFhLgEAAAAAAAAAAADkQg==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      min: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADI3MDMyNDY1NjBxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAyNzAzMjQ2
          NTYwcQFhLgEAAAAAAAAAAAAAAA==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    weather:
      max: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADI3MDMxODY1MjhxAlgDAAAAY3B1cQNLA050cQRRLoACXXEAWAoAAAAyNzAzMTg2
          NTI4cQFhLgMAAAAAAAAAZmb6QQAA4EAzMztC
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      min: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADI3MDMyNjA3MDRxAlgDAAAAY3B1cQNLA050cQRRLoACXXEAWAoAAAAyNzAzMjYw
          NzA0cQFhLgMAAAAAAAAAAABAwQAAAAAAAAAA
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
weight_decay: 5.0e-05
